### PR TITLE
#1 Add calculate route option

### LINKED ISSUE #1: Add `distancematrix` option for geocoder search
cc: @arpit1094

### PR DESCRIPTION
**Pull request by shailesh-kalamkar**
closes #1

### CODE REVIEW

**Review by arpit1094 — COMMENTED** [review]
@shailesh-kalamkar , can we rename this to something like HereCalculateRoute instead of HereCalculateMatrix ? As this filename does not give a clear cut idea about functionality IMO.

**Comment by shailesh-kalamkar** [comment]
@arpit1094 Done the suggested change. Also, made `mode` as a default param. Check this sample request

```
Geocoder.search("fastest;car;traffic:enabled", lookup: :here_calculate_route, params: {departure: "now", waypoint0: "52.5160,13.3779", waypoint1: "52.5206,13.3862"})
```

**Comment by shailesh-kalamkar** [comment]
@arpit1094 Added suggested changes for default params.

```
Geocoder.search({waypoint0: "52.5160,13.3779", waypoint1: "52.5206,13.3862"}, lookup: :here_calculate_route, params: {departure: "now", mode:"fastest;car;traffic:enabled"}) 
```

**Comment by arpit1094** [comment]
@shailesh-kalamkar , changed lookup to accept first argument as follows:
```
Geocoder.search([[52.5160,13.3779], [52.5206,13.3862]], lookup: :here_calculate_route, params: {departure: "now", mode:"fastest;car;traffic:enabled"}) 
```

IMO this style is more in sync with existing `geocoder` gem style, https://github.com/alexreisner/geocoder#basic-search

Merging this for now, let me know if we need further discussion on this change.

**Pull request merged**
